# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development: &default
  admin_name: First user
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 2310fe0ae230e45fd3c283d9d036ad1a4c295a22597ba396bfd10c0ea52c77e7a2d173f1f685e53d9c760bdaf4adacbcadf593e248191cf8b4544148c105d257
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  paypal_client_secret: <%= ENV["PAYPAL_CLIENT_SECRET"] %>
  host_name: "6e0fd751.ngrok.com"
  rollbar: '7f4b0337a9c14f069cb41c1738298fee'

test:
  <<: *default
  secret_key_base: f35ca4b2aa2dafad1dba50f7c8f9df784f4fc7b0550f1a843e359e32c4e092da56e63f7ddba7baec30543414b0064c00b4a1cc42b2efc5491ea13cf1e67cb084

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
